import json
import argparse
import os
from datetime import datetime

def generate_report(json_data, target_dir=None):
    # Determine if input is a file path or a raw JSON string
    if os.path.exists(json_data):
        with open(json_data, 'r') as f:
            try:
                data = json.load(f)
            except json.JSONDecodeError as e:
                print(f"Error parsing JSON from file: {e}")
                return
    else:
        try:
            data = json.loads(json_data)
        except json.JSONDecodeError as e:
            print(f"Error parsing JSON string: {e}")
            return
    
    # Extract data from the JSON structure
    client_name = data.get("client_name", "N/A")
    client_address = data.get("client_address", "N/A")
    company_name = data.get("company_name", "N/A")
    company_number = data.get("company_number", "N/A")
    ch_address = data.get("ch_address", "N/A")
    status = data.get("company_status", "N/A")
    date_of_inc = data.get("date_of_incorporation", "N/A")
    address_match = data.get("address_match", False)

    # Determine Risk Assessment and apply Legal Persona Rules
    risk_assessment = "**LOW RISK** - Data Consistent"
    
    if not address_match:
        risk_assessment = "**HIGH RISK** - Address Discrepancy Detected. Human review and secondary proof of address required."
    
    if status.lower() != "active" and status != "N/A":
        risk_assessment = f"**HIGH RISK** - Company Status is '{status}'. Flagged for human review."

    # Generate Markdown Report
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    report = f"""# Compliance Summary

**Date:** {timestamp}
**Data Source:** Companies House API & Client Input
**Generated By:** Automated Compliance Assistant

---

## 1. Client Details
- **Full Name:** {client_name}
- **Provided Address:** {client_address}

## 2. Verified Target Details (Companies House)
- **Company Name:** {company_name}
- **Company Number:** {company_number}
- **Status:** {status.capitalize() if status != "N/A" else status}
- **Date of Incorporation:** {date_of_inc}
- **Registered Office Address:** {ch_address}

---

## 3. Risk Assessment

> {risk_assessment}

### Assistant Notes
- *Action Required:* If flagged for High Risk, the conducting Lawyer must review discrepancy evidence.
- *Disclaimer:* The Automated Compliance Assistant provides data verification via public APIs. This report does not constitute legal interpretation.
"""
    
    # Save the report to a markdown file
    if company_number != "N/A":
        filename_suffix = company_number
    else:
        filename_suffix = "Unknown"
        
    # Determine output directory (Vercel uses /tmp)
    if not target_dir:
        is_vercel = os.getenv('VERCEL') == '1'
        output_dir = "/tmp/reports" if is_vercel else os.path.join(os.getcwd(), 'reports')
    else:
        output_dir = target_dir

    os.makedirs(output_dir, exist_ok=True)
    filename = f"Compliance_Report_{filename_suffix}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    filepath = os.path.join(output_dir, filename)
    
    try:
        with open(filepath, 'w') as f:
            f.write(report)
        print(f"Success! Compliance Report generated: {filepath}")
    except Exception as e:
        print(f"Failed to write report to file: {e}")
        print("\nFallback Report Output:\n", report)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate a clean Markdown Compliance Report from structured JSON.")
    parser.add_argument("source", help="The raw JSON string (or path to a .json file) containing the Onboarding-Captain's output.")
    args = parser.parse_args()
    
    generate_report(args.source)
